### ISSUE TITLE
Support flexible prefixes in ConfigServiceClient

### ISSUE THREAD

**Issue by jeromefroe** [m3db/m3cluster#114]
Currently, the client returned by `NewConfigServiceClient` hardcodes the prefix for keys as `_kv/`. It would be good to support other prefixes as well. One option is to not set a prefix in the client returned by `NewConfigServiceClient` and instead implement a wrapper function which implements the `Store` interface but appends a given prefix to all keys it is given. Etcd uses this approach in https://godoc.org/github.com/coreos/etcd/clientv3/namespace.

**Comment by cw9** [comment]
can't we change the API to KV(namespace string) and have the current users to do KV("_kv/"), new users like r2 to do KV("r2")?

**Comment by jeromefroe** [comment]
I'm fine with that approach as well. We can probably discuss further and decide on which approach to take before we begin the refactoring.
