### ISSUE TITLE
change config in puppet to set quota-backend-bytes

### ISSUE THREAD

**Issue by cw9** [m3db/m3cluster#118]

**Comment by prateek** [comment]
@cw9 Should this be internal?

**Comment by cw9** [comment]
@pjjw is this done?

**Comment by xichen2020** [comment]
I think @schallert has recently upgraded external cluster to 3.2 and is planning to set the quota backend bytes soon.

**Comment by pjjw** [comment]
yeah this was on hold until we moved to 3.2- there was resistance to moving
to 3.2 b/c of the confusing way etcd refers to api "versions" and the 3.2
client library requiring go 1.8, which we're still not using.

but chao's on vacation rn so :D :D :D

**Comment by xichen2020** [comment]
I think the client library in 3.1 is forward compatible with etcd 3.2, given that the external cluster has been upgraded to 3.2 and all the client code is still using 3.1 library and seems to be working.

@schallert probably has more details, though.

**Comment by schallert** [comment]
Yeah all of this is true. We're running 3.2 in some clusters and the "3.1" clients have been working fine with it.

**Comment by cw9** [comment]
@schallert any updates on this?
